export const accountGLColumns = [
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    style: "",
    showFilter: true,
    class: "text-left",
    style: "width:150px;",
    value: "",
  },
  {
    name: "clTitle",
    field: "clTitle",
    sortable: true,
    label: "گروه حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];

export const accountSLColumns = [
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    style: "",
    showFilter: true,
    class: "text-left",
    style: "width:150px;",
    value: "",
  },
  {
    name: "clTitle",
    field: "clTitle",
    sortable: true,
    label: "گروه حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "glTitle",
    field: "glTitle",
    sortable: true,
    label: "حساب کل",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];

export const accountDLColumns = [
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    style: "",
    showFilter: true,
    class: "text-left",
    style: "width:150px;",
    value: "",
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "debitRemained",
    field: "debitRemained",
    label: "مانده بدهکار",
    style: "width:120px;",
    class: "text-left",
  },
  {
    name: "creditRemained",
    field: "creditRemained",
    label: "مانده بستانکار",
    style: "width:120px;",
    class: "text-left",
  },
  {
    name: "typeId",
    field: "typeId",
    sortable: true,
    label: "نوع",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];
