import {
  year,
  month,
  date,
  day,
  summary,
  amount,
  taxAmount,
  insurranceAmount,
  customerName,
  salary,
  baseYear,
  housing,
  food,
  spouse,
  child,
  mission,
  overtime,
  reward,
  bonus,
  leave,
  serviceBenefit,
  addition,
  deduction,
  insurranceEmp,
  payable,
} from "src/constants/columns";

export const wageColumns = [
  year,
  month,
  date,
  summary,
  amount,
  taxAmount,
  insurranceAmount,
];

export const wageItemColumns = [
  { ...customerName, label: "پرسنل" },
  { ...day, showFilter: false },
  { ...salary, showFilter: false },
  { ...baseYear, showFilter: false },
  { ...housing, showFilter: false },
  { ...food, showFilter: false },
  { ...spouse, showFilter: false },
  { ...child, showFilter: false },
  { ...mission, showFilter: false },
  { ...overtime, showFilter: false },
  { ...reward, showFilter: false },
  { ...bonus, showFilter: false },
  { ...serviceBenefit, showFilter: false },
  { ...leave, showFilter: false },
  { ...addition, showFilter: false },
  { ...deduction, showFilter: false },
  { ...insurranceEmp, showFilter: false },
  { ...taxAmount, showFilter: false },
  { ...amount, showFilter: false },
  { ...payable, showFilter: false },
];
