import { sqlOperator } from "src/constants";
export const productColumns = [
  {
    name: "productGroupTitle",
    field: "productGroupTitle",
    sortable: true,
    label: "گروه کالا",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    class: "text-left",
    cellClass: "text-left",
    cellStyle: "",
    style: "width:130px;",
    showFilter: true,
    operator: sqlOperator.like,
    value: "",
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "typeId",
    field: "typeId",
    sortable: true,
    label: "نوع",
    style: "width:120px;",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "productUnitTitle",
    field: "productUnitTitle",
    sortable: true,
    label: "واحد سنجش",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "purchasePrice",
    field: "purchasePrice",
    sortable: true,
    label: "قیمت خرید",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "price",
    field: "price",
    sortable: true,
    label: "قیمت فروش",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];

export const bankBranchColumns = [
  {
    name: "bankTitle",
    field: "bankTitle",
    sortable: true,
    label: "بانک",
    class: "text-left",
    showFilter: true,
  },
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    showFilter: true,
    class: "text-left",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    class: "text-left",
    style: "width:120px",
    showFilter: true,
  },
  {
    name: "actions",
    sortable: false,
    showFilter: false,
    class: "text-left",
    style: "width:170px;",
  },
];

export const productUnitRelationColumns = [
  {
    name: "masterUnitTitle",
    field: "masterUnitTitle",
    label: "واحد سنجش اصلی",
    sortable: true,
    showFilter: true,
    class: "text-left",
  },
  {
    name: "detailUnitTitle",
    field: "detailUnitTitle",
    label: "واحد سنجش فرعی",
    sortable: true,
    showFilter: true,
    class: "text-left",
  },
  {
    name: "rate",
    field: "rate",
    label: "نرخ",
    sortable: true,
    showFilter: false,
    class: "text-left",
    style: "width:150px",
  },
];
