import { title, isActive, actions } from "src/constants/columns";
export const paymentInvoiceColumns = [
  {
    name: "no",
    field: "no",
    sortable: true,
    label: "شماره",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "date",
    field: "date",
    sortable: true,
    label: "تاریخ",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "amount",
    field: "amount",
    sortable: true,
    label: "مبلغ",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
];

export const bankAccountColumns = [
  {
    name: "bankTitle",
    field: "bankTitle",
    sortable: true,
    label: "بانک",
    style: "",
    showFilter: true,
    class: "text-left",
  },
  {
    name: "bankAccountTypeTitle",
    field: "bankAccountTypeTitle",
    sortable: true,
    label: "نوع حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "no",
    field: "no",
    sortable: true,
    label: "شماره حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "debitRemained",
    field: "debitRemained",
    sortable: true,
    label: "موجودی",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  isActive,
  actions,
];

export const cashColumns = [
  title,
  {
    name: "debitRemained",
    field: "debitRemained",
    sortable: true,
    label: "موجودی",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  isActive,
  actions,
];
