export const paymentInvoiceColumns = [
  {
    name: "no",
    field: "no",
    sortable: true,
    label: "شماره",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "date",
    field: "date",
    sortable: true,
    label: "تاریخ",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "amount",
    field: "amount",
    sortable: true,
    label: "مبلغ",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
];

export const bankAccountColumns = [
  {
    name: "bankTitle",
    field: "bankTitle",
    sortable: true,
    label: "بانک",
    style: "",
    showFilter: true,
    class: "text-left",
  },
  {
    name: "bankAccountTypeTitle",
    field: "bankAccountTypeTitle",
    sortable: true,
    label: "نوع حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "no",
    field: "no",
    sortable: true,
    label: "شماره حساب",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "debitRemained",
    field: "debitRemained",
    sortable: true,
    label: "موجودی",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];

export const cashColumns = [
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
  },
  {
    name: "debitRemained",
    field: "debitRemained",
    sortable: true,
    label: "موجودی",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];
