export const baseInfoColumns = [
  {
    name: "code",
    field: "code",
    sortable: true,
    label: "کد",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "title",
    field: "title",
    sortable: true,
    label: "عنوان",
    style: "",
    showFilter: true,
    class: "text-left",
    value: "",
  },
  {
    name: "isActive",
    field: "isActive",
    sortable: true,
    label: "فعال",
    align: "left",
    class: "text-left",
    style: "width:120px;",
    showFilter: true,
  },
  {
    name: "actions",
    field: "",
    sortable: false,
    label: "",
    align: "left",
    class: "text-left",
    style: "width:170px;",
    showFilter: false,
  },
];
